name: climbing_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  bloc: ^8.0.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3
  sqflite: ^2.3.3+1
  cloud_firestore: ^5.1.0
  syncfusion_flutter_charts: ^26.1.42
  syncfusion_flutter_sliders: ^26.1.42

  flutter_localizations:
    sdk: flutter

  flutter_gen: any
  path: ^1.9.0
  firebase_core: ^3.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
