// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEbaIvWq5HMUcUWWpYzq9-nG504s3eW5c',
    appId: '1:798691128233:web:b726670897ab4db43fcab8',
    messagingSenderId: '798691128233',
    projectId: 'climbing-app-2377b',
    authDomain: 'climbing-app-2377b.firebaseapp.com',
    databaseURL: 'https://climbing-app-2377b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'climbing-app-2377b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwjXG1Qxvla0tkiRIOcspsG6IVPfBWZCM',
    appId: '1:798691128233:android:ca786389d27c1c653fcab8',
    messagingSenderId: '798691128233',
    projectId: 'climbing-app-2377b',
    databaseURL: 'https://climbing-app-2377b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'climbing-app-2377b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoUBhzpbV-L54d_-PSIeA4ERFWmkEcCa0',
    appId: '1:798691128233:ios:e2ebdca47ba152ee3fcab8',
    messagingSenderId: '798691128233',
    projectId: 'climbing-app-2377b',
    databaseURL: 'https://climbing-app-2377b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'climbing-app-2377b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
